# wprowadzenie do numpy

In [5]:
imie = 'Olek'
print(imie)

Olek


In [6]:
dodawanie = 10 + 20
dodawanie

30

In [7]:
import numpy as np

In [8]:
tab = np.array([1, 2, 3, 4, 5])

In [9]:
tab * 5, tab + 10

(array([ 5, 10, 15, 20, 25]), array([11, 12, 13, 14, 15]))

In [10]:
tab = np.arange(10).shape(10, 10)
tab

TypeError: 'tuple' object is not callable

In [13]:
np.arange(1, 101).reshape(10,10) ** 2


array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [18]:
table = np.zeros((5, 5))
table[1:4, 1:4] = 1
table

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])